### ISSUE TITLE
Setup flask based REST API

### ISSUE THREAD

**Issue by ab-emptycup** [EmptyCupHQ/portfolio#4]
| Method | Route | Operation |
| -------- | ----- | ---------- | 
GET |      /  |  Fetches list of allowed routes|
GET |   /pros/ | List professionals |
POST | /pros/ | Add professional to directory |
GET |   /pros/__pid__ | Get profile data for professional with id _pid_ |
PUT | /pros/__pid__ | Update profile data for professional with id _pid_ |

**Comment by ab-emptycup** [comment]
@ashishraj-0 It seems an issue cannot be assigned to members outside the organisation unless they comment on the issue. Not sure about Github's access conventions. Either way, please consider this issue assigned to you.

**Comment by ashishRaj-0** [comment]
@ab-emptycup just for understanding and boiling down my work.
- I need to just create a Flask API for the mentioned endpoints.
- Are these endpoints can only accessed by a registered user

**Comment by ashishRaj-0** [comment]
@ab-emptycup so just to understand and boil down my work.
- I need to create a Flask API with the mentioned endpoints. 
  - So, to access these endpoints do a user to need to register and login to the site first or we are adding that part later?
- And do I also need to do the frontend for this or is that later?
  - If it is now itself, then can I just do the API for it first, get your review on it without the database integration and the frontend and then carry on with the other things

**Comment by ab-emptycup** [comment]
>       * So, to access these endpoints do a user to need to register and login to the site first or we are adding that part later?

Login happens through Firebase. Firebase is an independent auth service provider. Firebase auth happens directly in the frontend through javascript. There will be a Firebase Javascript SDK that opens a popup to authenticate the user and returns an "auth token". That auth token will be set as a HTTP header in the request to our backend api. Our backend api whenever it receives a request checks the header for the Auth-token. Then it uses firebase's python SDK to check the validity of that token. If the token is valid, then it responds to the request. Otherwise it returns auth failed.

We'll implement firebase authentication in a separate issue. For now you don't need to worry about auth. Just process the request for this issue. That's good enough.


>     * And do I also need to do the frontend for this or is that later?
>       
>       * If it is now itself, then can I just do the API for it first, get your review on it without the database integration and the frontend and then carry on with the other things

Yes, that's a good idea. Frontend is also part of v0.1 milestone. But, not part of this issue. You can just do the API part now. If you want to test the API, you can use [postman](https://www.postman.com/). It allows you craft and send HTTP requests to API endpoints.

**Comment by ashishRaj-0** [comment]
@ab-emptycup 
> POST	/pros/	Add professional to directory

For now, when registering the user, should the API generate the `uid` and the `active` data for the user, or will the requests already have this data in them?

And are there any other details from the `professional` data fields that the user will not enter but the API needs to generate for the user during the registration process?

**Comment by ab-emptycup** [comment]
Yes, you can generate the uuid for the user. There is a standard library
module in python to generate Uuid. You can use that. Later once we
implement firebase auth, the uuid will be generated by Firebase.

**Comment by ab-emptycup** [comment]
Closed by @ashishRaj-0 in #12
